//
// Generated file, do not edit! Created by opp_msgtool 6.0 from SensorMessage.msg.
//

#ifndef __SENSORMESSAGE_M_H
#define __SENSORMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class SensorMessage;
/**
 * Class generated from <tt>SensorMessage.msg:1</tt> by opp_msgtool.
 * <pre>
 * packet SensorMessage
 * {
 *     string SensorName;
 *     double sensedTime;
 *     double airHumidityValue;
 *     double airTemperatureValue;
 *     double soilDampnessValue;
 *     double soilTemperatureValue;
 *     double currentEnergyLevel;
 * }
 * </pre>
 */
class SensorMessage : public ::omnetpp::cPacket
{
  protected:
    omnetpp::opp_string SensorName;
    double sensedTime = 0;
    double airHumidityValue = 0;
    double airTemperatureValue = 0;
    double soilDampnessValue = 0;
    double soilTemperatureValue = 0;
    double currentEnergyLevel = 0;

  private:
    void copy(const SensorMessage& other);

  protected:
    bool operator==(const SensorMessage&) = delete;

  public:
    SensorMessage(const char *name=nullptr, short kind=0);
    SensorMessage(const SensorMessage& other);
    virtual ~SensorMessage();
    SensorMessage& operator=(const SensorMessage& other);
    virtual SensorMessage *dup() const override {return new SensorMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSensorName() const;
    virtual void setSensorName(const char * SensorName);

    virtual double getSensedTime() const;
    virtual void setSensedTime(double sensedTime);

    virtual double getAirHumidityValue() const;
    virtual void setAirHumidityValue(double airHumidityValue);

    virtual double getAirTemperatureValue() const;
    virtual void setAirTemperatureValue(double airTemperatureValue);

    virtual double getSoilDampnessValue() const;
    virtual void setSoilDampnessValue(double soilDampnessValue);

    virtual double getSoilTemperatureValue() const;
    virtual void setSoilTemperatureValue(double soilTemperatureValue);

    virtual double getCurrentEnergyLevel() const;
    virtual void setCurrentEnergyLevel(double currentEnergyLevel);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SensorMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SensorMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline SensorMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<SensorMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __SENSORMESSAGE_M_H

